server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MARCINDB
    username: root
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL55Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  async-thread-pool:
    max-threads: 10
