server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MARCINDB
    username: root
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jpa:
      repositories:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
