server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MARCINDB
    username: root
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jpa:
      repositories:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/security
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  enable-spring-security: false
app:
  async-thread-pool:
    max-threads: 10

jwt:
  auth:
    converter:
      resource-id: login-app
      principle-attribute: preferred_username

paths:
  /api/product:
    get:
      security:
        - my_oAuth_security_schema:
            - read_access

securitySchemes:
  my_oAuth_security_schema:
    type: oauth2
    flows:
      implicit:
        authorizationUrl: http://localhost:8080/oauth2/authorize
        scopes:
          read_access: read data
          write_access: modify data

keycloak:
  auth-server-url: http://localhost:8080/
  realm: security