create table product
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar(255)                            not null,
    price decimal(10, 2)                          not null,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE stock
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_quantity bigint                                  NOT NULL,
    product_id       bigint                                  NOT NULL REFERENCES product (id),
    CONSTRAINT pk_stock PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_product ON stock (product_id);

INSERT INTO product
    (id, name, price)
VALUES (1, 'Test Product', 10.00),
       (2, 'Test Product 2', 20.00),
       (3, 'Test Product 3', 30.00),
       (4, 'Test Product 4', 30.00),
       (5, 'Test Product 5', 30.00),
       (6, 'Test Product 6', 30.00),
       (7, 'Test Product 7', 30.00),
       (8, 'Test Product 8', 30.00);

INSERT INTO stock
    (current_quantity, product_id)
VALUES (10, 1),
       (20, 2),
       (5, 3);